name: homepage
description: nerg homepage
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=2.18.2 <3.5.0'
dependencies:
  flutter:
    sdk: flutter
  # rive: ^0.9.1
  # motion_sensors: ^0.1.0
  # audioplayers: ^1.1.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_rive_generator: 0.1.0
  flame_rive: ^1.6.0


flutter:
  uses-material-design: true
  assets:
    - assets/nerg.riv
    - assets/SalmonLake91bpm.ogg
